package com.hibernate.reverse.eng;

// Generated Feb 22, 2017 6:04:36 PM by Hibernate Tools 4.3.1

/**
 * HibernateSequence generated by hbm2java
 */
public class HibernateSequence implements java.io.Serializable {

	private Long nextVal;

	public HibernateSequence() {
	}

	public HibernateSequence(Long nextVal) {
		this.nextVal = nextVal;
	}

	public Long getNextVal() {
		return this.nextVal;
	}

	public void setNextVal(Long nextVal) {
		this.nextVal = nextVal;
	}

}
