package com.hibernate.reverse.engineering;

// Generated Feb 22, 2017 6:01:37 PM by Hibernate Tools 4.3.1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String lname;
	private String address;
	private Integer sal;

	public Employee() {
	}

	public Employee(String fname, String lname, String address, Integer sal) {
		this.fname = fname;
		this.lname = lname;
		this.address = address;
		this.sal = sal;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getSal() {
		return this.sal;
	}

	public void setSal(Integer sal) {
		this.sal = sal;
	}

}
