package com.hibernate.reverse.engineering;

// Generated Feb 22, 2017 6:01:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Student2 generated by hbm2java
 */
public class Student2 implements java.io.Serializable {

	private int sid;
	private String fname;
	private String lname;
	private Date dob;

	public Student2() {
	}

	public Student2(int sid) {
		this.sid = sid;
	}

	public Student2(int sid, String fname, String lname, Date dob) {
		this.sid = sid;
		this.fname = fname;
		this.lname = lname;
		this.dob = dob;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

}
